/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ui.manager; 

import ui.controller.ContractManagerController;
import dao.ContractDAO;
import entity.Contract;
import entity.ContractDetail;
import impl.ContractDAOImpl;
import impl.ContractDetailDAOImpl;
import java.io.File;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import utils.XDialog;
import dao.ContractDetailDAO;
import dao.TenantDAO;
import impl.TenantDAOImpl;
import java.awt.Frame;
import java.awt.Image;
import java.math.BigDecimal;
import java.text.SimpleDateFormat;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;





/**
 *
 * @author GAMING
 */
public class ContractManagerJDialog extends javax.swing.JDialog implements ContractManagerController{

    /**
     * Creates new form ContractManagerJDialog
     */
    public ContractManagerJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        open(); // phải gọi sau initComponents
        pack();
        txtIdContractManager.setEnabled(false);
        StartDate.setEnabled(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabs = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblContractManager = new javax.swing.JTable();
        btnCheckAll = new javax.swing.JButton();
        btnUnCheckAll = new javax.swing.JButton();
        btnDeleteCheckedItems = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        StartDate = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        EndDate = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Note = new javax.swing.JTextField();
        txtPaymentCycleMonth = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtDeposit_Amount = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtIdContractManager = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtIdRoom = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtTenant = new javax.swing.JTextField();
        ContractScanUrl = new javax.swing.JLabel();
        Reset = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        Update = new javax.swing.JButton();
        Create = new javax.swing.JButton();
        btnMoveFirst = new javax.swing.JButton();
        btnMovePrevious = new javax.swing.JButton();
        btnMoveNext = new javax.swing.JButton();
        btnMoveLast = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblContractManager.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã hợp đồng", "Mã phòng", "Mã người thuê", "Ngày bắt đầu", "Ngày kết thúc", "Tiền đặt cọc", "Tiền tháng", "Ảnh", "Ghi chú"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblContractManager.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblContractManagerMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblContractManager);

        btnCheckAll.setText("Chọn tất cả");
        btnCheckAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckAllActionPerformed(evt);
            }
        });

        btnUnCheckAll.setText("Hủy chọn tất cả");
        btnUnCheckAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnCheckAllActionPerformed(evt);
            }
        });

        btnDeleteCheckedItems.setText("Xóa các mục đã chọn");
        btnDeleteCheckedItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteCheckedItemsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 778, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCheckAll)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUnCheckAll)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeleteCheckedItems))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCheckAll)
                    .addComponent(btnUnCheckAll)
                    .addComponent(btnDeleteCheckedItems))
                .addContainerGap())
        );

        tabs.addTab("Thông tin cơ bản", jPanel1);

        StartDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartDateActionPerformed(evt);
            }
        });

        jLabel5.setText("Ngày bắt đầu");

        jLabel6.setText("Ngày kết thúc");

        EndDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EndDateActionPerformed(evt);
            }
        });

        jLabel7.setText("Ảnh hợp đồng");

        jLabel8.setText("Ghi chú");

        Note.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoteActionPerformed(evt);
            }
        });

        txtPaymentCycleMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPaymentCycleMonthActionPerformed(evt);
            }
        });

        jLabel10.setText("Tháng thanh toán");

        txtDeposit_Amount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDeposit_AmountActionPerformed(evt);
            }
        });

        jLabel11.setText("Tiền đặt cọc");

        txtIdContractManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdContractManagerActionPerformed(evt);
            }
        });

        jLabel12.setText("Mã hợp đồng");

        jLabel13.setText("Mã phòng");

        txtIdRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdRoomActionPerformed(evt);
            }
        });

        jLabel14.setText("Mã người thuê");

        txtTenant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenantActionPerformed(evt);
            }
        });

        ContractScanUrl.setText("Upload");
        ContractScanUrl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));
        ContractScanUrl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ContractScanUrlMouseClicked(evt);
            }
        });

        Reset.setText("Nhập mới");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });

        Delete.setText("Xóa");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        Update.setText("Cập nhật");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });

        Create.setText("Tạo mới");
        Create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateActionPerformed(evt);
            }
        });

        btnMoveFirst.setText("|<");

        btnMovePrevious.setText("<<");
        btnMovePrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMovePreviousActionPerformed(evt);
            }
        });

        btnMoveNext.setText(">>");
        btnMoveNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoveNextActionPerformed(evt);
            }
        });

        btnMoveLast.setText(">|");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(246, 246, 246)
                        .addComponent(jLabel6)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(ContractScanUrl, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Note)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(0, 287, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(251, 322, Short.MAX_VALUE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtIdContractManager)
                                            .addComponent(txtDeposit_Amount))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel14)
                                    .addComponent(txtIdRoom, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                                    .addComponent(txtTenant)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(StartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(EndDate))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(315, 315, 315)
                                        .addComponent(jLabel13))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtPaymentCycleMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(120, 120, 120))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(Create)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Update)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Delete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Reset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMoveFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnMovePrevious, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnMoveNext, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnMoveLast, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdContractManager, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdRoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDeposit_Amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtPaymentCycleMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EndDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Note, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ContractScanUrl, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Delete)
                        .addComponent(Reset)
                        .addComponent(btnMoveFirst)
                        .addComponent(btnMovePrevious)
                        .addComponent(btnMoveNext)
                        .addComponent(btnMoveLast))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Create)
                        .addComponent(Update))))
        );

        tabs.addTab("Thông tin thêm", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabs, javax.swing.GroupLayout.PREFERRED_SIZE, 778, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabs)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        // TODO add your handling code here:
         this.update();
    }//GEN-LAST:event_UpdateActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
        this.delete();
    }//GEN-LAST:event_DeleteActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        // TODO add your handling code here:
        this.clear();
    }//GEN-LAST:event_ResetActionPerformed

    private void btnMovePreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMovePreviousActionPerformed
        // TODO add your handling code here:
        this.movePrevious();
    }//GEN-LAST:event_btnMovePreviousActionPerformed

    private void btnMoveNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoveNextActionPerformed
        // TODO add your handling code here:
            this.moveNext();

    }//GEN-LAST:event_btnMoveNextActionPerformed

    private void StartDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StartDateActionPerformed

    private void EndDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EndDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EndDateActionPerformed

    private void txtContractScanUrlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContractScanUrlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContractScanUrlActionPerformed

    private void NoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NoteActionPerformed

    private void ContractScanUrlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ContractScanUrlMouseClicked
        // TODO add your handling code here:
        this.chooseFrontImage();
    }//GEN-LAST:event_ContractScanUrlMouseClicked

    private void CreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateActionPerformed
        // TODO add your handling code here:
        this.create();
    }//GEN-LAST:event_CreateActionPerformed

    private void btnCheckAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckAllActionPerformed
        // TODO add your handling code here:
        this.checkAll();
    }//GEN-LAST:event_btnCheckAllActionPerformed

    private void btnUnCheckAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnCheckAllActionPerformed
        // TODO add your handling code here:
        this.uncheckAll();
    }//GEN-LAST:event_btnUnCheckAllActionPerformed

    private void btnDeleteCheckedItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteCheckedItemsActionPerformed
        // TODO add your handling code here:
        this.delete();
    }//GEN-LAST:event_btnDeleteCheckedItemsActionPerformed

    private void tblContractManagerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblContractManagerMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            this.edit();
        }
    }//GEN-LAST:event_tblContractManagerMouseClicked
        /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContractManagerJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContractManagerJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContractManagerJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContractManagerJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ContractManagerJDialog dialog = new ContractManagerJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ContractScanUrl;
    private javax.swing.JButton Create;
    private javax.swing.JButton Delete;
    private javax.swing.JTextField EndDate;
    private javax.swing.JTextField Note;
    private javax.swing.JButton Reset;
    private javax.swing.JTextField StartDate;
    private javax.swing.JButton Update;
    private javax.swing.JButton btnCheckAll;
    private javax.swing.JButton btnDeleteCheckedItems;
    private javax.swing.JButton btnMoveFirst;
    private javax.swing.JButton btnMoveLast;
    private javax.swing.JButton btnMoveNext;
    private javax.swing.JButton btnMovePrevious;
    private javax.swing.JButton btnUnCheckAll;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane tabs;
    private javax.swing.JTable tblContractManager;
    private javax.swing.JTextField txtDeposit_Amount;
    private javax.swing.JTextField txtIdContractManager;
    private javax.swing.JTextField txtIdRoom;
    private javax.swing.JTextField txtPaymentCycleMonth;
    private javax.swing.JTextField txtTenant;
    // End of variables declaration//GEN-END:variables

    ContractDAO dao = new ContractDAOImpl();
    ContractDetailDAO contractDetailDAO = new ContractDetailDAOImpl();
    List<Contract> items = List.of();
    private ContractDetail currentDetail = null;
    TenantDAO tenantDAO = new TenantDAOImpl();



 @Override
    public void open() {
        this.setLocationRelativeTo(null);
        this.fillToTable();
        this.clear();

    }
private void showContractTenantManager() {
        ContractTenantManagerJDialog dialog = new ContractTenantManagerJDialog((Frame) this.getOwner(), true); 
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
    }
    
@Override
public void fillToTable() {
    DefaultTableModel model = (DefaultTableModel) tblContractManager.getModel();
    model.setRowCount(0);

    try {
        items = dao.findAll();
        for (Contract item : items) {
            System.out.println(item.getId());
            System.out.println(item.getPaymentCycleMonths());
            Object[] rowData = {
                item.getId(),                    
                item.getRoomId(),              
                item.getTenant(),               
                item.getStartDate(),           
                item.getEndDate(),              
                item.getDepositAmount(),        
                item.getPaymentCycleMonths(), 
                item.getFile_scan_url(),
                item.getNotes()
            };
            model.addRow(rowData);
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Lỗi khi tải dữ liệu hợp đồng: " + e.getMessage());
        e.printStackTrace();
    }
}

@Override
    public void edit() {
        int row = tblContractManager.getSelectedRow();
        if (row >= 0 && row < items.size()) {
            Contract entity = items.get(row);
            setForm(entity);
            ContractDetail detail = contractDetailDAO.findById(entity.getId().toString());
            setDetailForm(detail);
            setEditable(true);
            tabs.setSelectedIndex(1);
        }
       
    }

@Override
public void checkAll() {
    this.setCheckedAll(true);
}

@Override
public void uncheckAll() {
    this.setCheckedAll(false);
}

private void setCheckedAll(boolean checked) {
    for (int i = 0; i < tblContractManager.getRowCount(); i++) {
        if (tblContractManager.getColumnCount() > 5) { // cột 5 là cột check
            tblContractManager.setValueAt(checked, i, 4);
        }
    }
}

@Override
public void deleteCheckedItems() {
    if (XDialog.confirm("Bạn thực sự muốn xóa các mục chọn?")) {
        for (int i = 0; i < tblContractManager.getRowCount(); i++) {
            Boolean checked = (Boolean) tblContractManager.getValueAt(i, 4); // Cột 4 là "Tháng thanh toán"
            if (Boolean.TRUE.equals(checked)) {
                Contract item = items.get(i);
                dao.deleteById(item.getId().toString());
            }
        }
        this.fillToTable();
    }
}


 @Override
    public void setForm(Contract entity) {
        if (entity == null) return;

        txtIdContractManager.setText(entity.getId() == null ? "" : entity.getId().toString());
        txtIdRoom.setText(entity.getRoomId() == null ? "" : entity.getRoomId().toString());
        txtTenant.setText(entity.getTenant() == null ? "" : entity.getTenant());
        txtDeposit_Amount.setText(entity.getDepositAmount() == null ? "" : entity.getDepositAmount().toString());

        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        StartDate.setText(entity.getStartDate() == null ? "" : sdf.format(entity.getStartDate()));
        EndDate.setText(entity.getEndDate() == null ? "" : sdf.format(entity.getEndDate()));
        ContractScanUrl.setText(entity.getFile_scan_url() == null ? "" : entity.getFile_scan_url());
        Note.setText(entity.getNotes() == null ? "" : entity.getNotes());
        txtPaymentCycleMonth.setText(String.valueOf(entity.getPaymentCycleMonths()));

    }

@Override
    public Contract getForm() {
        return getForm(false); 
    }    

public Contract getForm(boolean isCreate) {
    Contract entity = new Contract();
        if (!isCreate && !txtIdContractManager.getText().isEmpty()) {
            entity.setId(Integer.parseInt(txtIdContractManager.getText()));
        } 
    try {
        entity.setId(Integer.parseInt(txtIdContractManager.getText()));
    } catch (NumberFormatException e) {
        entity.setId(null);
    }

    try {
        entity.setRoomId(Integer.parseInt(txtIdRoom.getText()));
    } catch (NumberFormatException e) {
        entity.setRoomId(null);
    }

    entity.setTenant(txtTenant.getText());

    try {
        entity.setDepositAmount(new BigDecimal(txtDeposit_Amount.getText()));
    } catch (NumberFormatException e) {
        entity.setDepositAmount(BigDecimal.ZERO);
    }

    try {
        entity.setStartDate(new SimpleDateFormat("yyyy-MM-dd").parse(StartDate.getText()));
    } catch (Exception e) {
        entity.setStartDate(null);
    }

    try {
        entity.setEndDate(new SimpleDateFormat("yyyy-MM-dd").parse(EndDate.getText()));
    } catch (Exception e) {
        entity.setEndDate(null);
    }

    entity.setFile_scan_url(ContractScanUrl.getText());
    entity.setNotes(Note.getText());

    try {
        entity.setPaymentCycleMonths(Integer.valueOf(txtPaymentCycleMonth.getText()));
    } catch (NumberFormatException e) {
        entity.setPaymentCycleMonths((Integer) 1);
    }

    return entity;
}

private ContractDetail getDetailForm() {
    ContractDetail detail = new ContractDetail();
    detail.setId(txtIdContractManager.getText());
    detail.setRoomId(txtIdRoom.getText());
    detail.setTenant(txtTenant.getText());
    detail.setStartDate(StartDate.getText());
    detail.setEndDate(EndDate.getText());
    detail.setDepositAmount(txtDeposit_Amount.getText());
    try {
        detail.setPaymentCycleMonths(Integer.parseInt(txtPaymentCycleMonth.getText()));
    } catch (NumberFormatException e) {
        detail.setPaymentCycleMonths(0);
    }
    detail.setFileScanUrl(ContractScanUrl.getText());
    detail.setNotes(Note.getText());
    return detail;
}

private void setDetailForm(ContractDetail detail) {
        if (detail == null) return;

        txtIdContractManager.setText(detail.getId());
        txtIdRoom.setText(detail.getRoomId());
        txtTenant.setText(detail.getTenant());
        StartDate.setText(detail.getStartDate());
        EndDate.setText(detail.getEndDate());
        txtDeposit_Amount.setText(detail.getDepositAmount());
        txtPaymentCycleMonth.setText(String.valueOf(detail.getPaymentCycleMonths()));
        ContractScanUrl.setText(detail.getFileScanUrl());
        Note.setText(detail.getNotes());
    }


@Override
public void create() {
    try {
        int roomId = Integer.parseInt(txtIdRoom.getText());
        if (roomId < 1 || roomId > 40) {
            JOptionPane.showMessageDialog(this, "Mã phòng chỉ từ 1 đến 40.");
            return;
        }

        String tenantId = txtTenant.getText().trim();

        if (!tenantId.matches("\\d+")) {
            JOptionPane.showMessageDialog(this, "CCCD không được chứa chữ cái. Vui lòng nhập số.");
            return;
        }

        if (tenantDAO.findById(tenantId) == null) {
            JOptionPane.showMessageDialog(this, "Mã CCCD người thuê không tồn tại!");
            return;
        }

        Date startDate = new Date();

        String endDateText = EndDate.getText().trim();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        sdf.setLenient(false);
        Date endDate;
        try {
            endDate = sdf.parse(endDateText);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Ngày kết thúc không đúng định dạng yyyy-MM-dd.");
            return;
        }

        Contract tenant = getForm();
        tenant.setStartDate(startDate); 
        tenant.setEndDate(endDate);     

        ContractDetail detail = getDetailForm();

        dao.create(tenant);
        contractDetailDAO.create(detail);

        fillToTable();
        clear();

        JOptionPane.showMessageDialog(this, "Thêm hợp đồng thành công!");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Lỗi khi tạo hợp đồng: " + e.getMessage());
        e.printStackTrace();
    }
}

@Override
public void update() {
    Contract tenant = getForm();
    ContractDetail detail = getDetailForm();

    dao.update(tenant);
    contractDetailDAO.update(detail);

    fillToTable();
    this.clear();
}

@Override
public void delete() {
    if (XDialog.confirm("Bạn thực sự muốn xóa?")) {
        String id = txtIdContractManager.getText();
        dao.deleteById(id);
        this.fillToTable();
        this.clear();
    }
}

@Override
public void clear() {
    this.setForm(new Contract());
    this.setDetailForm(null);
    this.setEditable(false);
    txtPaymentCycleMonth.setText("");
}

 @Override
    public void setEditable(boolean editable) {
        
        txtIdContractManager.setEditable(!editable);
        txtIdRoom.setEditable(!editable);
        txtTenant.setEditable(true);
        txtDeposit_Amount.setEditable(true);
        txtPaymentCycleMonth.setEditable(true);
        ContractScanUrl.setEnabled(false);
        Note.setEditable(true);
        StartDate.setEditable(true);
        EndDate.setEditable(true);

        Create.setEnabled(!editable);
        Update.setEnabled(editable);
        Delete.setEnabled(editable);

        int rowCount = tblContractManager.getRowCount();
        btnMoveFirst.setEnabled(rowCount > 0);
        btnMovePrevious.setEnabled(rowCount > 0);
        btnMoveNext.setEnabled(rowCount > 0);
        btnMoveLast.setEnabled(rowCount > 0);
    }

@Override
public void moveFirst() {
    this.moveTo(0);
}

@Override
public void movePrevious() {
    this.moveTo(tblContractManager.getSelectedRow() - 1);
}

@Override
public void moveNext() {
    this.moveTo(tblContractManager.getSelectedRow() + 1);
}

@Override
public void moveLast() {
    this.moveTo(tblContractManager.getRowCount() - 1);
}

@Override
public void moveTo(int index) {
    if (index < 0) {
        this.moveLast();
    } else if (index >= tblContractManager.getRowCount()) {
        this.moveFirst();
    } else {
        tblContractManager.clearSelection();
        tblContractManager.setRowSelectionInterval(index, index);
        this.edit();
    }
}

private void chooseFrontImage() {
    JFileChooser chooser = new JFileChooser();
    chooser.setFileFilter(new FileNameExtensionFilter("Image files", "jpg", "jpeg", "png"));
    int result = chooser.showOpenDialog(this);
    if (result == JFileChooser.APPROVE_OPTION) {
        File file = chooser.getSelectedFile();  
        ContractScanUrl.setText(file.getAbsolutePath());
    }
}
private void txtPaymentCycleMonthActionPerformed(java.awt.event.ActionEvent evt) {
    // Không cần xử lý gì cả
}

private void txtDeposit_AmountActionPerformed(java.awt.event.ActionEvent evt) {
    // Không cần xử lý gì cả
}

private void txtIdContractManagerActionPerformed(java.awt.event.ActionEvent evt) {
    // Không cần xử lý gì cả
}

private void txtIdRoomActionPerformed(java.awt.event.ActionEvent evt) {
    // Không cần xử lý gì cả
}

private void txtTenantActionPerformed(java.awt.event.ActionEvent evt) {
    // Không cần xử lý gì cả
}

}
