/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ui.manager;

import dao.ContractDAO;
import entity.Contract;
import entity.ContractDetail;
import impl.ContractDAOImpl;
import impl.ContractDetailDAOImpl;
import java.io.File;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import utils.XDialog;
import dao.ContractDetailDAO;
import java.math.BigDecimal;
import java.text.SimpleDateFormat;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;





/**
 *
 * @author GAMING
 */
public class ContractManagerJDialog extends javax.swing.JDialog implements ContractManagerController{

    /**
     * Creates new form ContractManagerJDialog
     */
    public ContractManagerJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        open(); // phải gọi sau initComponents
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabs = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblContractManager = new javax.swing.JTable();
        txtIdContractManager = new javax.swing.JTextField();
        txtIdRoom = new javax.swing.JTextField();
        txtDeposit_Amount = new javax.swing.JTextField();
        txtTenant = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtPaymentCycleMonth = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        StartDate = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        EndDate = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtContractScanUrl = new javax.swing.JTextField();
        Note = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblContractManager2 = new javax.swing.JTable();
        chooseFrontImage = new javax.swing.JButton();
        Create = new javax.swing.JButton();
        Update = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        Reset = new javax.swing.JButton();
        btnMoveFirst = new javax.swing.JButton();
        btnMovePrevious = new javax.swing.JButton();
        btnMoveNext = new javax.swing.JButton();
        btnMoveLast = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Mã hợp đồng");

        jLabel2.setText("Mã phòng");

        jLabel3.setText("Tiền đặt cọc");

        jLabel4.setText("Mã người thuê");

        tblContractManager.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã hợp đồng", "Mã phòng", "Tiền đặt cọc", "Mã người thuê", "Tháng Thanh Toán"
            }
        ));
        jScrollPane1.setViewportView(tblContractManager);

        txtIdContractManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdContractManagerActionPerformed(evt);
            }
        });

        txtIdRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdRoomActionPerformed(evt);
            }
        });

        txtDeposit_Amount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDeposit_AmountActionPerformed(evt);
            }
        });

        txtTenant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenantActionPerformed(evt);
            }
        });

        jLabel9.setText("Tháng thanh toán");

        txtPaymentCycleMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPaymentCycleMonthActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtIdContractManager, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtIdRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(128, 128, 128)
                                .addComponent(jLabel2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(126, 126, 126)
                                .addComponent(jLabel4))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtDeposit_Amount, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTenant, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPaymentCycleMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdContractManager, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdRoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDeposit_Amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtPaymentCycleMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        tabs.addTab("Thông tin cơ bản", jPanel1);

        StartDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartDateActionPerformed(evt);
            }
        });

        jLabel5.setText("Ngày bắt đầu");

        jLabel6.setText("Ngày kết thúc");

        EndDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EndDateActionPerformed(evt);
            }
        });

        jLabel7.setText("Ảnh hợp đồng");

        jLabel8.setText("Ghi chú");

        txtContractScanUrl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContractScanUrlActionPerformed(evt);
            }
        });

        Note.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoteActionPerformed(evt);
            }
        });

        tblContractManager2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Ngày bắt đầu", "Ngày kết thúc", "Ảnh hợp đồng", "Ghi chú"
            }
        ));
        jScrollPane2.setViewportView(tblContractManager2);

        chooseFrontImage.setText("Chọn ảnh");
        chooseFrontImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseFrontImageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(199, 199, 199))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(StartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(EndDate, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(txtContractScanUrl, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(chooseFrontImage))
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(Note, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(86, 86, 86))))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EndDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtContractScanUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Note, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chooseFrontImage))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabs.addTab("Thông tin thêm", jPanel2);

        Create.setText("Tạo mới");

        Update.setText("Cập nhật");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });

        Delete.setText("Xóa");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        Reset.setText("Nhập mới");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });

        btnMoveFirst.setText("|<");

        btnMovePrevious.setText("<<");
        btnMovePrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMovePreviousActionPerformed(evt);
            }
        });

        btnMoveNext.setText(">>");
        btnMoveNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoveNextActionPerformed(evt);
            }
        });

        btnMoveLast.setText(">|");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabs)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Create)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Update)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Delete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Reset)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMoveFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMovePrevious, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMoveNext, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMoveLast, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabs, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Delete)
                        .addComponent(Reset)
                        .addComponent(btnMoveFirst)
                        .addComponent(btnMovePrevious)
                        .addComponent(btnMoveNext)
                        .addComponent(btnMoveLast))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Create)
                        .addComponent(Update))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdContractManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdContractManagerActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtIdContractManagerActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        // TODO add your handling code here:
         this.update();
    }//GEN-LAST:event_UpdateActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
        this.delete();
    }//GEN-LAST:event_DeleteActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        // TODO add your handling code here:
        this.clear();
    }//GEN-LAST:event_ResetActionPerformed

    private void btnMovePreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMovePreviousActionPerformed
        // TODO add your handling code here:
        this.movePrevious();
    }//GEN-LAST:event_btnMovePreviousActionPerformed

    private void btnMoveNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoveNextActionPerformed
        // TODO add your handling code here:
            this.moveNext();

    }//GEN-LAST:event_btnMoveNextActionPerformed

    private void chooseFrontImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseFrontImageActionPerformed
        // TODO add your handling code here:
        this.chooseFrontImage();
    }//GEN-LAST:event_chooseFrontImageActionPerformed

    private void txtIdRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdRoomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdRoomActionPerformed

    private void txtDeposit_AmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDeposit_AmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDeposit_AmountActionPerformed

    private void txtTenantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenantActionPerformed

    private void txtPaymentCycleMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPaymentCycleMonthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPaymentCycleMonthActionPerformed

    private void StartDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StartDateActionPerformed

    private void EndDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EndDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EndDateActionPerformed

    private void txtContractScanUrlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContractScanUrlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContractScanUrlActionPerformed

    private void NoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NoteActionPerformed
        /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContractManagerJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContractManagerJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContractManagerJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContractManagerJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ContractManagerJDialog dialog = new ContractManagerJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Create;
    private javax.swing.JButton Delete;
    private javax.swing.JTextField EndDate;
    private javax.swing.JTextField Note;
    private javax.swing.JButton Reset;
    private javax.swing.JTextField StartDate;
    private javax.swing.JButton Update;
    private javax.swing.JButton btnMoveFirst;
    private javax.swing.JButton btnMoveLast;
    private javax.swing.JButton btnMoveNext;
    private javax.swing.JButton btnMovePrevious;
    private javax.swing.JButton chooseFrontImage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane tabs;
    private javax.swing.JTable tblContractManager;
    private javax.swing.JTable tblContractManager2;
    private javax.swing.JTextField txtContractScanUrl;
    private javax.swing.JTextField txtDeposit_Amount;
    private javax.swing.JTextField txtIdContractManager;
    private javax.swing.JTextField txtIdRoom;
    private javax.swing.JTextField txtPaymentCycleMonth;
    private javax.swing.JTextField txtTenant;
    // End of variables declaration//GEN-END:variables

ContractDAO dao = new ContractDAOImpl();
    ContractDetailDAO contractDetailDAO = new ContractDetailDAOImpl();
    List<Contract> items = List.of();
    private ContractDetail currentDetail = null;


 @Override
    public void open() {
        this.setLocationRelativeTo(null);
        this.fillToTable();
        this.clear();

        tblContractManager.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                this.edit();
            }
        });

        tblContractManager.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 1) {
                    edit();
                }
            }
        });
    }

@Override
    public void fillToTable() {
        DefaultTableModel model = (DefaultTableModel) tblContractManager.getModel();
        model.setRowCount(0);
        items = dao.findAll();
        items.forEach(item -> {
            Object[] rowData = {
                item.getId(),
                item.getRoomId(),
                item.getDepositAmount(),
                item.getTenant(),
                item.getPayment_cycle_months()
            };
            model.addRow(rowData);
        });
    }

@Override
    public void edit() {
        int row = tblContractManager.getSelectedRow();
        if (row >= 0 && row < items.size()) {
            Contract entity = items.get(row);
            setForm(entity);
            ContractDetail detail = contractDetailDAO.findById(entity.getId().toString());
            setDetailForm(detail);
            setEditable(true);
            tabs.setSelectedIndex(0);
        }
    }

@Override
public void checkAll() {
    this.setCheckedAll(true);
}

@Override
public void uncheckAll() {
    this.setCheckedAll(false);
}

private void setCheckedAll(boolean checked) {
    for (int i = 0; i < tblContractManager.getRowCount(); i++) {
        if (tblContractManager.getColumnCount() > 5) { // cột 5 là cột check
            tblContractManager.setValueAt(checked, i, 4);
        }
    }
}

@Override
public void deleteCheckedItems() {
    if (XDialog.confirm("Bạn thực sự muốn xóa các mục chọn?")) {
        for (int i = 0; i < tblContractManager.getRowCount(); i++) {
            Boolean checked = (Boolean) tblContractManager.getValueAt(i, 4); // Cột 4 là "Tháng thanh toán"
            if (Boolean.TRUE.equals(checked)) {
                Contract item = items.get(i);
                dao.deleteById(item.getId().toString());
            }
        }
        this.fillToTable();
    }
}


 @Override
    public void setForm(Contract entity) {
        if (entity == null) return;

        txtIdContractManager.setText(entity.getId() == null ? "" : entity.getId().toString());
        txtIdRoom.setText(entity.getRoomId() == null ? "" : entity.getRoomId().toString());
        txtTenant.setText(entity.getTenant() == null ? "" : entity.getTenant());
        txtDeposit_Amount.setText(entity.getDepositAmount() == null ? "" : entity.getDepositAmount().toString());

        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        StartDate.setText(entity.getStartDate() == null ? "" : sdf.format(entity.getStartDate()));
        EndDate.setText(entity.getEndDate() == null ? "" : sdf.format(entity.getEndDate()));
        txtContractScanUrl.setText(entity.getFile_scan_url() == null ? "" : entity.getFile_scan_url());
        Note.setText(entity.getNotes() == null ? "" : entity.getNotes());
        txtPaymentCycleMonth.setText(entity.getPayment_cycle_months() == null ? "1" : entity.getPayment_cycle_months().toString());
    }


@Override
public Contract getForm() {
    Contract entity = new Contract();
    try {
        entity.setId(Integer.parseInt(txtIdContractManager.getText()));
    } catch (NumberFormatException e) {
        entity.setId(null);
    }

    try {
        entity.setRoomId(Integer.parseInt(txtIdRoom.getText()));
    } catch (NumberFormatException e) {
        entity.setRoomId(null);
    }

    entity.setTenant(txtTenant.getText());

    try {
        entity.setDepositAmount(new BigDecimal(txtDeposit_Amount.getText()));
    } catch (NumberFormatException e) {
        entity.setDepositAmount(BigDecimal.ZERO);
    }

    try {
        entity.setStartDate(new SimpleDateFormat("yyyy-MM-dd").parse(StartDate.getText()));
    } catch (Exception e) {
        entity.setStartDate(null);
    }

    try {
        entity.setEndDate(new SimpleDateFormat("yyyy-MM-dd").parse(EndDate.getText()));
    } catch (Exception e) {
        entity.setEndDate(null);
    }

    entity.setFile_scan_url(txtContractScanUrl.getText());
    entity.setNotes(Note.getText());

    try {
        entity.setPayment_cycle_months(Integer.parseInt(txtPaymentCycleMonth.getText()));
    } catch (NumberFormatException e) {
        entity.setPayment_cycle_months(1);
    }

    return entity;
}

private ContractDetail getDetailForm() {
    ContractDetail detail = new ContractDetail();
    detail.setId(txtIdContractManager.getText());
    detail.setRoomId(txtIdRoom.getText());
    detail.setTenant(txtTenant.getText());
    detail.setStartDate(StartDate.getText());
    detail.setEndDate(EndDate.getText());
    detail.setDepositAmount(txtDeposit_Amount.getText());
    try {
        detail.setPaymentCycleMonths(Integer.parseInt(txtPaymentCycleMonth.getText()));
    } catch (NumberFormatException e) {
        detail.setPaymentCycleMonths(0);
    }
    detail.setFileScanUrl(txtContractScanUrl.getText());
    detail.setNotes(Note.getText());
    return detail;
}

private void setDetailForm(ContractDetail detail) {
        if (detail == null) return;

        txtIdContractManager.setText(detail.getId());
        txtIdRoom.setText(detail.getRoomId());
        txtTenant.setText(detail.getTenant());
        StartDate.setText(detail.getStartDate());
        EndDate.setText(detail.getEndDate());
        txtDeposit_Amount.setText(detail.getDepositAmount());
        txtPaymentCycleMonth.setText(String.valueOf(detail.getPaymentCycleMonths()));
        txtContractScanUrl.setText(detail.getFileScanUrl());
        Note.setText(detail.getNotes());
    }


@Override
public void create() {
    Contract tenant = getForm();
    ContractDetail detail = getDetailForm();

    dao.create(tenant);
    contractDetailDAO.create(detail);

    fillToTable();
    clear();
}

@Override
public void update() {
    Contract tenant = getForm();
    ContractDetail detail = getDetailForm();

    dao.update(tenant);
    contractDetailDAO.update(detail);

    fillToTable();
}

@Override
public void delete() {
    if (XDialog.confirm("Bạn thực sự muốn xóa?")) {
        String id = txtIdContractManager.getText();
        dao.deleteById(id);
        this.fillToTable();
        this.clear();
    }
}

@Override
public void clear() {
    this.setForm(new Contract());
    this.setDetailForm(null);
    this.setEditable(false);
}

 @Override
    public void setEditable(boolean editable) {
        txtIdContractManager.setEditable(!editable);
        txtIdRoom.setEditable(!editable);
        txtTenant.setEditable(true);
        txtDeposit_Amount.setEditable(true);
        txtPaymentCycleMonth.setEditable(true);
        txtContractScanUrl.setEditable(true);
        Note.setEditable(true);
        StartDate.setEditable(true);
        EndDate.setEditable(true);

        Create.setEnabled(!editable);
        Update.setEnabled(editable);
        Delete.setEnabled(editable);

        int rowCount = tblContractManager.getRowCount();
        btnMoveFirst.setEnabled(rowCount > 0);
        btnMovePrevious.setEnabled(rowCount > 0);
        btnMoveNext.setEnabled(rowCount > 0);
        btnMoveLast.setEnabled(rowCount > 0);
    }

@Override
public void moveFirst() {
    this.moveTo(0);
}

@Override
public void movePrevious() {
    this.moveTo(tblContractManager.getSelectedRow() - 1);
}

@Override
public void moveNext() {
    this.moveTo(tblContractManager.getSelectedRow() + 1);
}

@Override
public void moveLast() {
    this.moveTo(tblContractManager.getRowCount() - 1);
}

@Override
public void moveTo(int index) {
    if (index < 0) {
        this.moveLast();
    } else if (index >= tblContractManager.getRowCount()) {
        this.moveFirst();
    } else {
        tblContractManager.clearSelection();
        tblContractManager.setRowSelectionInterval(index, index);
        this.edit();
    }
}

private void chooseFrontImage() {
    JFileChooser chooser = new JFileChooser();
    chooser.setFileFilter(new FileNameExtensionFilter("Image files", "jpg", "jpeg", "png"));
    int result = chooser.showOpenDialog(this);
    if (result == JFileChooser.APPROVE_OPTION) {
        File file = chooser.getSelectedFile();
        txtContractScanUrl.setText(file.getAbsolutePath());
    }
}
}
