
package ui.manager;

import java.awt.Frame;
import java.math.BigDecimal;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.html.parser.Entity;

import dao.ContractDAO;
import dao.InvoiceDao;
import entity.Invoice;
import impl.ContractDAOImpl;
import impl.InvoiceDAOImpl;
import ui.controller.InvoicesManagerController;
import utils.XDialog;

/**
 *
 * @author GAMING
 */
public class InvoicesManagerJDialog extends javax.swing.JDialog implements InvoicesManagerController {

    /**
     * Creates new form InvoicesManagerJDialog
     */
    public InvoicesManagerJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        loadInvoicesToTable();
        txtIdInvoice.setEnabled(false);
        txtCreatedAt.setEnabled(false);
        TblInvoices.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                int row = TblInvoices.getSelectedRow();
                if (row >= 0) {
                    txtIdInvoice.setText(TblInvoices.getValueAt(row, 0).toString());
                    txtIdContract.setText(TblInvoices.getValueAt(row, 1).toString());
                    txtBillingPeriodMonth.setText(TblInvoices.getValueAt(row, 2).toString());
                    txtBillingPeriodYear.setText(TblInvoices.getValueAt(row, 3).toString());
                    txtPreviousDebt.setText(TblInvoices.getValueAt(row, 4).toString());
                    txtDiscount.setText(TblInvoices.getValueAt(row, 5).toString());
                    txtTotalamount.setText(TblInvoices.getValueAt(row, 6).toString());
                    txtStatus.setText(TblInvoices.getValueAt(row, 7).toString());
                    txtDueDate.setText(TblInvoices.getValueAt(row, 8).toString());
                    txtCreatedAt.setText(TblInvoices.getValueAt(row, 9).toString());
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField13 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblInvoices = new javax.swing.JTable();
        btnCheckAll = new javax.swing.JButton();
        btnUnCheckAll = new javax.swing.JButton();
        btnDeleteCheckedItems = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtBillingPeriodYear = new javax.swing.JTextField();
        Create1 = new javax.swing.JButton();
        Update1 = new javax.swing.JButton();
        Delete1 = new javax.swing.JButton();
        Reset1 = new javax.swing.JButton();
        btnMoveFirst1 = new javax.swing.JButton();
        btnMovePrevious1 = new javax.swing.JButton();
        btnMoveNext1 = new javax.swing.JButton();
        btnMoveLast1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtIdInvoice = new javax.swing.JTextField();
        txtIdContract = new javax.swing.JTextField();
        txtDiscount = new javax.swing.JTextField();
        txtTotalamount = new javax.swing.JTextField();
        txtStatus = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtCreatedAt = new javax.swing.JTextField();
        txtDueDate = new javax.swing.JTextField();
        txtBillingPeriodMonth = new javax.swing.JTextField();
        txtPreviousDebt = new javax.swing.JTextField();
        btnViewInvoicesManager = new javax.swing.JButton();
        Reset = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        Update = new javax.swing.JButton();
        Create = new javax.swing.JButton();
        btnMoveFirst = new javax.swing.JButton();
        btnMovePrevious = new javax.swing.JButton();
        btnMoveNext = new javax.swing.JButton();
        btnMoveLast = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        TblInvoices.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null, null, null, null, null, null, null, null },
                        { null, null, null, null, null, null, null, null, null, null },
                        { null, null, null, null, null, null, null, null, null, null },
                        { null, null, null, null, null, null, null, null, null, null }
                },
                new String[] {
                        "Mã hóa đơn", "Mã hợp đồng", "Tiền tháng", "Tiền năm", "Nợ cũ", "Giảm giá", "Tổng",
                        "Trạng thái", "Ngày hết hạn", "Ngày tạo"
                }));
        TblInvoices.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TblInvoicesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TblInvoices);

        btnCheckAll.setText("Chọn tất cả");
        btnCheckAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckAllActionPerformed(evt);
            }
        });

        btnUnCheckAll.setText("Hủy chọn tất cả");
        btnUnCheckAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnCheckAllActionPerformed(evt);
            }
        });

        btnDeleteCheckedItems.setText("Xóa các mục đã chọn");
        btnDeleteCheckedItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteCheckedItemsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 783, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCheckAll)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnUnCheckAll)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDeleteCheckedItems)
                                .addContainerGap()));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 318,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnCheckAll)
                                        .addComponent(btnUnCheckAll)
                                        .addComponent(btnDeleteCheckedItems))
                                .addContainerGap(15, Short.MAX_VALUE)));

        jTabbedPane1.addTab("Danh sách", jPanel1);

        jLabel7.setText("Hóa đơn năm:");

        jLabel9.setText("Hóa đơn tháng");

        jLabel10.setText("Nợ cũ");

        Create1.setText("Tạo mới");

        Update1.setText("Cập nhật");
        Update1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Update1ActionPerformed(evt);
            }
        });

        Delete1.setText("Xóa");
        Delete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete1ActionPerformed(evt);
            }
        });

        Reset1.setText("Nhập mới");
        Reset1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Reset1ActionPerformed(evt);
            }
        });

        btnMoveFirst1.setText("|<");

        btnMovePrevious1.setText("<<");
        btnMovePrevious1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMovePrevious1ActionPerformed(evt);
            }
        });

        btnMoveNext1.setText(">>");
        btnMoveNext1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoveNext1ActionPerformed(evt);
            }
        });

        btnMoveLast1.setText(">|");

        jLabel11.setText("Mã hóa đơn");

        jLabel12.setText("Giảm giá");

        jLabel13.setText("Trạng thái");

        jLabel14.setText("Ngày thanh toán");

        jLabel15.setText("Tổng");

        jLabel16.setText("Mã hợp đồng");

        txtIdContract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdContractActionPerformed(evt);
            }
        });

        jLabel17.setText("Ngày hết hạn");

        jLabel18.setText("Tạo vào:");

        txtPreviousDebt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPreviousDebtActionPerformed(evt);
            }
        });

        btnViewInvoicesManager.setText("Xem sử dụng hóa đơn chi tiết");
        btnViewInvoicesManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewInvoicesManagerActionPerformed(evt);
            }
        });

        Reset.setText("Nhập mới");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });

        Delete.setText("Xóa");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        Update.setText("Cập nhật");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });

        Create.setText("Tạo mới");
        Create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateActionPerformed(evt);
            }
        });

        btnMoveFirst.setText("|<");
        btnMoveFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoveFirstActionPerformed(evt);
            }
        });

        btnMovePrevious.setText("<<");
        btnMovePrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMovePreviousActionPerformed(evt);
            }
        });

        btnMoveNext.setText(">>");
        btnMoveNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoveNextActionPerformed(evt);
            }
        });

        btnMoveLast.setText(">|");
        btnMoveLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoveLastActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(Create1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Update1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Delete1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Reset1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnMoveFirst1, javax.swing.GroupLayout.PREFERRED_SIZE, 44,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnMovePrevious1, javax.swing.GroupLayout.PREFERRED_SIZE, 47,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnMoveNext1, javax.swing.GroupLayout.PREFERRED_SIZE, 47,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnMoveLast1, javax.swing.GroupLayout.PREFERRED_SIZE, 44,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGroup(jPanel3Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                                .addGroup(jPanel3Layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabel11)
                                                                        .addComponent(jLabel13)
                                                                        .addComponent(jLabel12))
                                                                .addGap(239, 239, 239)
                                                                .addGroup(jPanel3Layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabel15)
                                                                        .addComponent(jLabel16)
                                                                        .addComponent(jLabel10,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                73,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addComponent(jLabel14)
                                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                                .addComponent(txtDiscount,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 272,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(txtTotalamount,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 272,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                                .addGroup(jPanel3Layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(txtStatus,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                272,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jLabel9)
                                                                        .addComponent(txtDueDate,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                272,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(txtBillingPeriodMonth,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                272,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(jPanel3Layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(txtBillingPeriodYear,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                272,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                                                .addGap(6, 6, 6)
                                                                                .addComponent(jLabel18,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        90,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addComponent(jLabel7,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                90,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(txtCreatedAt,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                272,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(txtPreviousDebt,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                272,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addContainerGap(221, Short.MAX_VALUE))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGroup(jPanel3Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                                .addComponent(txtIdInvoice,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 272,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(txtIdContract,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 272,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(31, 31, 31)
                                                                .addComponent(btnViewInvoicesManager))
                                                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(0, 4, Short.MAX_VALUE))))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(Create)
                                .addGap(4, 4, 4)
                                .addComponent(Update)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Delete)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Reset)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnMoveFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 44,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnMovePrevious, javax.swing.GroupLayout.PREFERRED_SIZE, 47,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnMoveNext, javax.swing.GroupLayout.PREFERRED_SIZE, 47,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnMoveLast, javax.swing.GroupLayout.PREFERRED_SIZE, 44,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap()));
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel16)
                                        .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtIdInvoice, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtIdContract, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnViewInvoicesManager))
                                .addGap(11, 11, 11)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel15)
                                        .addComponent(jLabel12))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanel3Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(txtDiscount,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txtTotalamount,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel13))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(30, 30, 30)
                                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtPreviousDebt, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(7, 7, 7)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtBillingPeriodYear, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtBillingPeriodMonth, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel17)
                                        .addComponent(jLabel18))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtCreatedAt, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtDueDate, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(Create)
                                        .addComponent(Delete)
                                        .addComponent(Update)
                                        .addComponent(Reset)
                                        .addComponent(btnMoveFirst)
                                        .addComponent(btnMovePrevious)
                                        .addComponent(btnMoveNext)
                                        .addComponent(btnMoveLast))
                                .addGap(123, 123, 123)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(Delete1)
                                                .addComponent(Reset1)
                                                .addComponent(btnMoveFirst1)
                                                .addComponent(btnMovePrevious1)
                                                .addComponent(btnMoveNext1)
                                                .addComponent(btnMoveLast1))
                                        .addGroup(jPanel3Layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(Create1)
                                                .addComponent(Update1))
                                        .addComponent(jLabel14))
                                .addGap(18, 18, 18)));

        jTabbedPane1.addTab("Biểu Mẫu", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jTabbedPane1)
                                .addContainerGap()));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 409, Short.MAX_VALUE));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdContractActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtIdContractActionPerformed

    }// GEN-LAST:event_txtIdContractActionPerformed

    private void TblInvoicesMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_TblInvoicesMouseClicked

        if (evt.getClickCount() == 2) {
            int row = TblInvoices.getSelectedRow();
            if (row >= 0) {
                edit();
            }
        }
    }// GEN-LAST:event_TblInvoicesMouseClicked

    private void Update1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_Update1ActionPerformed

    }// GEN-LAST:event_Update1ActionPerformed

    private void Delete1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_Delete1ActionPerformed

    }// GEN-LAST:event_Delete1ActionPerformed

    private void Reset1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_Reset1ActionPerformed

    }// GEN-LAST:event_Reset1ActionPerformed

    private void btnMovePrevious1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnMovePrevious1ActionPerformed

    }// GEN-LAST:event_btnMovePrevious1ActionPerformed

    private void btnMoveNext1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnMoveNext1ActionPerformed

    }// GEN-LAST:event_btnMoveNext1ActionPerformed

    private void btnMoveNextActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnMoveNextActionPerformed

        this.moveNext();
    }// GEN-LAST:event_btnMoveNextActionPerformed

    private void btnMovePreviousActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnMovePreviousActionPerformed

        this.movePrevious();

    }// GEN-LAST:event_btnMovePreviousActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ResetActionPerformed

        clearForm();
    }// GEN-LAST:event_ResetActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_UpdateActionPerformed

        this.update();
    }// GEN-LAST:event_UpdateActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_DeleteActionPerformed

        this.delete();
    }// GEN-LAST:event_DeleteActionPerformed

    private void CreateActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_CreateActionPerformed

        this.create();
    }// GEN-LAST:event_CreateActionPerformed

    private void txtPreviousDebtActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtPreviousDebtActionPerformed

    }// GEN-LAST:event_txtPreviousDebtActionPerformed

    private void btnMoveFirstActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnMoveFirstActionPerformed

        this.moveFirst();
    }// GEN-LAST:event_btnMoveFirstActionPerformed

    private void btnMoveLastActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnMoveLastActionPerformed

        this.moveLast();
    }// GEN-LAST:event_btnMoveLastActionPerformed

    private void btnViewInvoicesManagerActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnViewInvoicesManagerActionPerformed

        this.showInvoiceDetailsManagerJDialog();
    }// GEN-LAST:event_btnViewInvoicesManagerActionPerformed

    private void btnCheckAllActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnCheckAllActionPerformed

        this.checkAll();
    }// GEN-LAST:event_btnCheckAllActionPerformed

    private void btnUnCheckAllActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnUnCheckAllActionPerformed

        this.uncheckAll();
    }// GEN-LAST:event_btnUnCheckAllActionPerformed

    private void btnDeleteCheckedItemsActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnDeleteCheckedItemsActionPerformed

        this.deleteCheckedItems();
    }// GEN-LAST:event_btnDeleteCheckedItemsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InvoicesManagerJDialog.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InvoicesManagerJDialog.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InvoicesManagerJDialog.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InvoicesManagerJDialog.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                InvoicesManagerJDialog dialog = new InvoicesManagerJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Create;
    private javax.swing.JButton Create1;
    private javax.swing.JButton Delete;
    private javax.swing.JButton Delete1;
    private javax.swing.JButton Reset;
    private javax.swing.JButton Reset1;
    private javax.swing.JTable TblInvoices;
    private javax.swing.JButton Update;
    private javax.swing.JButton Update1;
    private javax.swing.JButton btnCheckAll;
    private javax.swing.JButton btnDeleteCheckedItems;
    private javax.swing.JButton btnMoveFirst;
    private javax.swing.JButton btnMoveFirst1;
    private javax.swing.JButton btnMoveLast;
    private javax.swing.JButton btnMoveLast1;
    private javax.swing.JButton btnMoveNext;
    private javax.swing.JButton btnMoveNext1;
    private javax.swing.JButton btnMovePrevious;
    private javax.swing.JButton btnMovePrevious1;
    private javax.swing.JButton btnUnCheckAll;
    private javax.swing.JButton btnViewInvoicesManager;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField txtBillingPeriodMonth;
    private javax.swing.JTextField txtBillingPeriodYear;
    private javax.swing.JTextField txtCreatedAt;
    private javax.swing.JTextField txtDiscount;
    private javax.swing.JTextField txtDueDate;
    private javax.swing.JTextField txtIdContract;
    private javax.swing.JTextField txtIdInvoice;
    private javax.swing.JTextField txtPreviousDebt;
    private javax.swing.JTextField txtStatus;
    private javax.swing.JTextField txtTotalamount;
    // End of variables declaration//GEN-END:variables
    InvoiceDao dao = new InvoiceDAOImpl();
    ContractDAO contractDAO = new ContractDAOImpl();
    private InvoiceDao invoiceDAO = new InvoiceDAOImpl();
    private List<Invoice> listInvoices = new ArrayList<>();
    private int currentIndex = -1;

    private void showInvoiceDetailsManagerJDialog() {
        InvoiceDetailsManagerJDialog dialog = new InvoiceDetailsManagerJDialog((Frame) this.getOwner(), true);
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
    }

    private void loadInvoicesToTable() {
        DefaultTableModel model = (DefaultTableModel) TblInvoices.getModel();
        model.setRowCount(0);

        listInvoices = invoiceDAO.findAll();

        for (Invoice i : listInvoices) {
            model.addRow(new Object[] {
                    i.getId(),
                    i.getContractid(),
                    i.getBilling_period_month(),
                    i.getBilling_period_year(),
                    i.getPrevious_debt(),
                    i.getDiscount(),
                    i.getTotalamount(),
                    i.getStatus() ? "Đã thanh toán" : "Chưa thanh toán",
                    i.getDue_date(),
                    i.getCreated_at()
            });
        }
    }

    private void setFormInvoice(Invoice i) {
        txtIdInvoice.setText(String.valueOf(i.getId()));
        txtIdContract.setText(String.valueOf(i.getContractid()));
        txtBillingPeriodMonth.setText(String.valueOf(i.getBilling_period_month()));
        txtBillingPeriodYear.setText(String.valueOf(i.getBilling_period_year()));
        txtPreviousDebt.setText(String.valueOf(i.getPrevious_debt()));
        txtDiscount.setText(String.valueOf(i.getDiscount()));
        txtTotalamount.setText(String.valueOf(i.getTotalamount()));
        txtStatus.setText(i.getStatus() ? "1" : "0");
        txtDueDate.setText(i.getDue_date() != null ? i.getDue_date().toString() : "");
        txtCreatedAt.setText(i.getCreated_at() != null ? i.getCreated_at().toString() : "");
    }

    private void fillToForm(int index) {
        if (index < 0 || index >= listInvoices.size())
            return;

        Invoice i = listInvoices.get(index);
        txtIdInvoice.setText(String.valueOf(i.getId()));
        txtIdContract.setText(String.valueOf(i.getContractid()));
        txtBillingPeriodMonth.setText(String.valueOf(i.getBilling_period_month()));
        txtBillingPeriodYear.setText(String.valueOf(i.getBilling_period_year()));
        txtPreviousDebt.setText(String.valueOf(i.getPrevious_debt()));
        txtDiscount.setText(String.valueOf(i.getDiscount()));
        txtTotalamount.setText(String.valueOf(i.getTotalamount()));
        txtStatus.setText(i.getStatus() ? "1" : "0");
        txtDueDate.setText(i.getDue_date() != null ? i.getDue_date().toString() : "");
        txtCreatedAt.setText(i.getCreated_at() != null ? i.getCreated_at().toString() : "");
    }

    private void clearForm() {
        txtIdInvoice.setText("");
        txtIdContract.setText("");
        txtBillingPeriodMonth.setText("");
        txtBillingPeriodYear.setText("");
        txtPreviousDebt.setText("");
        txtDiscount.setText("");
        txtTotalamount.setText("");
        txtStatus.setText("");
        txtDueDate.setText("");
        txtCreatedAt.setText("");
        currentIndex = -1;
    }

    public void moveTo(int index) {
        if (index < 0) {
            moveLast();
        } else if (index >= TblInvoices.getRowCount()) {
            moveFirst();
        } else {
            TblInvoices.setRowSelectionInterval(index, index);
            edit();
        }
    }

    @Override
    public void moveFirst() {
        if (TblInvoices.getRowCount() > 0) {
            moveTo(0);
        }
    }

    @Override
    public void moveLast() {
        int rowCount = TblInvoices.getRowCount();
        if (rowCount > 0) {
            moveTo(rowCount - 1);
        }
    }

    public void edit() {
        int row = TblInvoices.getSelectedRow();
        if (row >= 0) {

            String id = TblInvoices.getValueAt(row, 0).toString();
            Invoice invoice = invoiceDAO.findById(id);
            if (invoice != null) {
                setFormInvoice(invoice);
            }
        }
    }

    private Invoice getFormInvoice() {
        Invoice invoice = new Invoice();

        try {
            invoice.setId(Integer.parseInt(txtIdInvoice.getText()));
        } catch (NumberFormatException e) {
            invoice.setId(0);
        }

        try {
            invoice.setContractid(Integer.parseInt(txtIdContract.getText()));
        } catch (NumberFormatException e) {
            invoice.setContractid(0);
        }

        try {
            invoice.setBilling_period_month(Integer.parseInt(txtBillingPeriodMonth.getText()));
        } catch (NumberFormatException e) {
            invoice.setBilling_period_month(0);
        }

        try {
            invoice.setBilling_period_year(Integer.parseInt(txtBillingPeriodYear.getText()));
        } catch (NumberFormatException e) {
            invoice.setBilling_period_year(0);
        }

        try {
            invoice.setPrevious_debt(new java.math.BigDecimal(txtPreviousDebt.getText()));
        } catch (NumberFormatException e) {
            invoice.setPrevious_debt(java.math.BigDecimal.ZERO);
        }

        try {
            invoice.setDiscount(new java.math.BigDecimal(txtDiscount.getText()));
        } catch (NumberFormatException e) {
            invoice.setDiscount(java.math.BigDecimal.ZERO);
        }

        try {
            invoice.setTotalamount(new java.math.BigDecimal(txtTotalamount.getText()));
        } catch (NumberFormatException e) {
            invoice.setTotalamount(java.math.BigDecimal.ZERO);
        }

        invoice.setStatus("1".equals(txtStatus.getText()));

        try {
            invoice.setDue_date(java.sql.Date.valueOf(txtDueDate.getText()));
        } catch (IllegalArgumentException e) {
            invoice.setDue_date(null);
        }

        try {
            invoice.setCreated_at(java.sql.Date.valueOf(txtCreatedAt.getText()));
        } catch (IllegalArgumentException e) {
            invoice.setCreated_at(null);
        }

        return invoice;
    }

    @Override
    public void open() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from
                                                                       // nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void setForm(Entity entity) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from
                                                                       // nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public Entity getForm() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from
                                                                       // nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void fillToTable() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from
                                                                       // nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void create() {
        try {
            Invoice invoice = new Invoice();

            String contractIdStr = txtIdContract.getText().trim();
            if (contractIdStr.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập Mã hợp đồng", "Thông báo",
                        JOptionPane.WARNING_MESSAGE);
                return;
            }
            int contractId;
            try {
                contractId = Integer.parseInt(contractIdStr);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Tạo mới Mã hợp đồng là chữ", "Lỗi nhập liệu",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (!contractDAO.existsById(contractId)) {
                JOptionPane.showMessageDialog(this, "❌ Mã hợp đồng không tồn tại!", "Thông báo",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }
            invoice.setContractid(contractId);

            Date now = new Date();
            invoice.setCreated_at(now);

            @SuppressWarnings("deprecation")
            int month = now.getMonth() + 1;
            @SuppressWarnings("deprecation")
            int year = now.getYear() + 1900;
            invoice.setBilling_period_month(month);
            invoice.setBilling_period_year(year);

            // Ngày hết hạn
            String dueDateStr = txtDueDate.getText().trim();
            if (dueDateStr.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Tạo mới trống Ngày hết hạn", "Thông báo",
                        JOptionPane.WARNING_MESSAGE);
                return;
            }
            Date dueDate;
            try {
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                dueDate = sdf.parse(dueDateStr);
            } catch (ParseException e) {
                JOptionPane.showMessageDialog(this, "Tạo mới Ngày hết hạn sai định dạng (yyyy-MM-dd)", "Lỗi định dạng",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }
            invoice.setDue_date(dueDate);

            // Nợ cũ
            String prevDebtStr = txtPreviousDebt.getText().trim();
            if (prevDebtStr.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Tạo mới trống Nợ cũ", "Thông báo", JOptionPane.WARNING_MESSAGE);
                return;
            }
            try {
                invoice.setPrevious_debt(new BigDecimal(prevDebtStr));
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Tạo mới Nợ cũ là chữ", "Lỗi nhập liệu", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Giảm giá
            String discountStr = txtDiscount.getText().trim();
            if (discountStr.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Tạo mới trống Giảm giá", "Thông báo", JOptionPane.WARNING_MESSAGE);
                return;
            }
            try {
                invoice.setDiscount(new BigDecimal(discountStr));
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Tạo mới Giảm giá là chữ", "Lỗi nhập liệu",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Tổng tiền
            String totalStr = txtTotalamount.getText().trim();
            if (totalStr.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Tạo mới trống Tổng", "Thông báo", JOptionPane.WARNING_MESSAGE);
                return;
            }
            try {
                invoice.setTotalamount(new BigDecimal(totalStr));
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Tạo mới Tổng là chữ", "Lỗi nhập liệu", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Trạng thái
            String statusStr = txtStatus.getText().trim();
            if (statusStr.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Tạo mới trống Trạng thái", "Thông báo",
                        JOptionPane.WARNING_MESSAGE);
                return;
            }

            if (statusStr.equalsIgnoreCase("Chưa thanh toán")) {
                invoice.setStatus(false);
            } else if (statusStr.equalsIgnoreCase("Đã thanh toán")) {
                invoice.setStatus(true);
            } else {
                JOptionPane.showMessageDialog(this,
                        "Trạng thái không hợp lệ! Chỉ được nhập: 'Chưa thanh toán' hoặc 'Đã thanh toán'.",
                        "Lỗi nhập liệu", JOptionPane.ERROR_MESSAGE);
                return;
            }

            invoiceDAO.create(invoice);
            loadInvoicesToTable();
            clearForm();

            JOptionPane.showMessageDialog(this, "✔ Tạo hóa đơn thành công!", "Thành công",
                    JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "❗ Đã xảy ra lỗi: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }

    @Override
    public void update() {
        try {
            Invoice invoice = new Invoice();

            String contractIdStr = txtIdContract.getText().trim();
            if (contractIdStr.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Cập nhật trống Mã hợp đồng", "Thông báo",
                        JOptionPane.WARNING_MESSAGE);
                return;
            }
            int contractId;
            try {
                contractId = Integer.parseInt(contractIdStr);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Cập nhật Mã hợp đồng là chữ", "Lỗi nhập liệu",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (!contractDAO.existsById(contractId)) {
                JOptionPane.showMessageDialog(this, "❌ Mã hợp đồng không tồn tại!", "Thông báo",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }
            invoice.setContractid(contractId);

            // Hóa đơn tháng
            String monthStr = txtBillingPeriodMonth.getText().trim();
            if (monthStr.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Cập nhật trống Hóa đơn tháng", "Thông báo",
                        JOptionPane.WARNING_MESSAGE);
                return;
            }
            try {
                invoice.setBilling_period_month(Integer.parseInt(monthStr));
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Cập nhật Hóa đơn tháng là chữ", "Lỗi nhập liệu",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Hóa đơn năm
            String yearStr = txtBillingPeriodYear.getText().trim();
            if (yearStr.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Cập nhật trống Hóa đơn năm", "Thông báo",
                        JOptionPane.WARNING_MESSAGE);
                return;
            }
            try {
                invoice.setBilling_period_year(Integer.parseInt(yearStr));
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Cập nhật Hóa đơn năm là chữ", "Lỗi nhập liệu",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }

            String dueDateStr = txtDueDate.getText().trim();
            if (dueDateStr.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Cập nhật trống Ngày hết hạn", "Thông báo",
                        JOptionPane.WARNING_MESSAGE);
                return;
            }
            Date dueDate;
            try {
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                dueDate = sdf.parse(dueDateStr);
            } catch (ParseException e) {
                JOptionPane.showMessageDialog(this, "Cập nhật Ngày hết hạn sai định dạng (yyyy-MM-dd)", "Lỗi định dạng",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }
            invoice.setDue_date(dueDate);

            String prevDebtStr = txtPreviousDebt.getText().trim();
            if (prevDebtStr.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Cập nhật trống Nợ cũ", "Thông báo", JOptionPane.WARNING_MESSAGE);
                return;
            }
            try {
                invoice.setPrevious_debt(new BigDecimal(prevDebtStr));
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Cập nhật Nợ cũ là chữ", "Lỗi nhập liệu",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }

            String discountStr = txtDiscount.getText().trim();
            if (discountStr.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Cập nhật trống Giảm giá", "Thông báo",
                        JOptionPane.WARNING_MESSAGE);
                return;
            }
            try {
                invoice.setDiscount(new BigDecimal(discountStr));
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Cập nhật Giảm giá là chữ", "Lỗi nhập liệu",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }

            String totalStr = txtTotalamount.getText().trim();
            if (totalStr.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Cập nhật trống Tổng", "Thông báo", JOptionPane.WARNING_MESSAGE);
                return;
            }
            try {
                invoice.setTotalamount(new BigDecimal(totalStr));
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Cập nhật Tổng là chữ", "Lỗi nhập liệu", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Trạng thái
            String statusStr = txtStatus.getText().trim();
            if (statusStr.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Cập nhật trống Trạng thái", "Thông báo",
                        JOptionPane.WARNING_MESSAGE);
                return;
            }
            try {
                int statusInt = Integer.parseInt(statusStr);
                invoice.setStatus(statusInt == 1);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Cập nhật Trạng thái là chữ", "Lỗi nhập liệu",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }

            invoiceDAO.update(invoice);
            loadInvoicesToTable();

            JOptionPane.showMessageDialog(this, "✔ Cập nhật hóa đơn thành công!", "Thành công",
                    JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "❗ Đã xảy ra lỗi: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }

    @Override
    public void delete() {
        int selectedRow = TblInvoices.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn dòng cần xóa!");
            return;
        }

        if (XDialog.confirm("Bạn thực sự muốn xóa?")) {
            String id = txtIdInvoice.getText();
            dao.deleteById(id);
            this.fillToTable();
            this.clear();
        }
    }

    @Override
    public void clear() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from
                                                                       // nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void setEditable(boolean editable) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from
                                                                       // nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void checkAll() {
        TblInvoices.getSelectionModel().setValueIsAdjusting(true);
        if (TblInvoices.getRowCount() > 0) {
            TblInvoices.setRowSelectionInterval(0, TblInvoices.getRowCount() - 1);
        }

        TblInvoices.getSelectionModel().setValueIsAdjusting(false);

        JOptionPane.showMessageDialog(this, "Đã chọn tất cả!");
    }

    @Override
    public void uncheckAll() {
        if (TblInvoices.getSelectedRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Không có dòng nào để bỏ chọn!");
            return;
        }

        TblInvoices.clearSelection();
        JOptionPane.showMessageDialog(this, "Đã hủy chọn tất cả!");
    }

    @Override
    public void deleteCheckedItems() {
        if (XDialog.confirm("Bạn thực sự muốn xóa?")) {
            String id = txtIdInvoice.getText();
            dao.deleteById(id);
            this.fillToTable();
            this.clear();
        }
    }

    @Override
    public void movePrevious() {
        int selectedRow = TblInvoices.getSelectedRow();
        if (selectedRow > 0) {
            moveTo(selectedRow - 1);
        }
    }

    @Override
    public void moveNext() {
        int selectedRow = TblInvoices.getSelectedRow();
        if (selectedRow >= 0 && selectedRow < TblInvoices.getRowCount() - 1) {
            moveTo(selectedRow + 1);
        }
    }

}
