
package ui.manager;

import java.math.BigDecimal;
import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import dao.InvoiceDetailDao;
import entity.InvoiceDetail;
import impl.InvoiceDetailDAOImpl;
import ui.controller.InvoiceDetailsManagerController;
import utils.XDialog;

/**
 *
 * @author GAMING
 */
public class InvoiceDetailsManagerJDialog extends javax.swing.JDialog implements InvoiceDetailsManagerController {

    private InvoiceDetailDao dao = new InvoiceDetailDAOImpl();
    private int row = -1;

    /**
     * Creates new form InvoiceDetailsManagerJDialog
     */
    public InvoiceDetailsManagerJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        fillToTable();
        tblInvoiceDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int row = tblInvoiceDetails.getSelectedRow();
                if (row >= 0) {
                    String id = tblInvoiceDetails.getValueAt(row, 2).toString();
                    InvoiceDetail detail = dao.findById(id);
                    if (detail != null) {
                        setForm(detail);
                        tabs.setSelectedIndex(1);
                        open();
                    }
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        tabs = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblInvoiceDetails = new javax.swing.JTable();
        btnCheckAll = new javax.swing.JButton();
        btnUnCheckAll = new javax.swing.JButton();
        btnDeleteCheckedItems = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        txtIdInvoice = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtSeviceId = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        txtInvoiceId = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        txtUnitprice = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnMoveNext = new javax.swing.JButton();
        btnMoveLast = new javax.swing.JButton();
        btnMovePrevious = new javax.swing.JButton();
        btnMoveFirst = new javax.swing.JButton();
        Reset = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        Update = new javax.swing.JButton();
        Create = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null }
                },
                new String[] {
                        "Title 1", "Title 2", "Title 3", "Title 4"
                }));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tblInvoiceDetails.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null, null, null, null },
                        { null, null, null, null, null, null },
                        { null, null, null, null, null, null },
                        { null, null, null, null, null, null }
                },
                new String[] {
                        "Mã hóa đơn chi tiết", "Mã hóa đơn", "Mã dịch vụ", "Số lượng", "Giá tiền", "Tổng"
                }));
        jScrollPane2.setViewportView(tblInvoiceDetails);

        btnCheckAll.setText("Chọn tất cả");
        btnCheckAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckAllActionPerformed(evt);
            }
        });

        btnUnCheckAll.setText("Hủy chọn tất cả");
        btnUnCheckAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnCheckAllActionPerformed(evt);
            }
        });

        btnDeleteCheckedItems.setText("Xóa các mục đã chọn");
        btnDeleteCheckedItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteCheckedItemsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 676, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCheckAll)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnUnCheckAll)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDeleteCheckedItems)
                                .addContainerGap()));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnCheckAll)
                                        .addComponent(btnUnCheckAll)
                                        .addComponent(btnDeleteCheckedItems))
                                .addGap(0, 0, Short.MAX_VALUE)));

        tabs.addTab("Danh Sách", jPanel1);

        jLabel12.setText("Mã hóa đơn chi tiết");

        txtIdInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdInvoiceActionPerformed(evt);
            }
        });

        jLabel11.setText("Mã dịch vụ");

        txtSeviceId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSeviceIdActionPerformed(evt);
            }
        });

        jLabel14.setText("Số lượng");

        txtQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantityActionPerformed(evt);
            }
        });

        txtInvoiceId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInvoiceIdActionPerformed(evt);
            }
        });

        jLabel13.setText("Mã hóa đơn");

        jLabel6.setText("Tổng");

        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });

        txtUnitprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUnitpriceActionPerformed(evt);
            }
        });

        jLabel5.setText("Giá tiền");

        btnMoveNext.setText(">>");
        btnMoveNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoveNextActionPerformed(evt);
            }
        });

        btnMoveLast.setText(">|");
        btnMoveLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoveLastActionPerformed(evt);
            }
        });

        btnMovePrevious.setText("<<");
        btnMovePrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMovePreviousActionPerformed(evt);
            }
        });

        btnMoveFirst.setText("|<");
        btnMoveFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoveFirstActionPerformed(evt);
            }
        });

        Reset.setText("Nhập mới");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });

        Delete.setText("Xóa");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        Update.setText("Cập nhật");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });

        Create.setText("Tạo mới");
        Create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel12)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel13)
                                                .addGap(284, 284, 284))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel11)
                                                        .addGroup(jPanel2Layout
                                                                .createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.TRAILING,
                                                                        false)
                                                                .addComponent(txtIdInvoice,
                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE, 312,
                                                                        Short.MAX_VALUE)
                                                                .addComponent(txtSeviceId,
                                                                        javax.swing.GroupLayout.Alignment.LEADING))
                                                        .addComponent(txtUnitprice,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 312,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(26, 26, 26)
                                                .addGroup(jPanel2Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                267, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel14)
                                                        .addComponent(txtInvoiceId,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 265,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txtQuantity,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 265,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel6))
                                                .addGap(0, 71, Short.MAX_VALUE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(Create)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(Update)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(Delete)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(Reset)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnMoveFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 44,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btnMovePrevious, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btnMoveNext, javax.swing.GroupLayout.PREFERRED_SIZE, 47,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btnMoveLast, javax.swing.GroupLayout.PREFERRED_SIZE, 44,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))));
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel12)
                                        .addComponent(jLabel13))
                                .addGap(10, 10, 10)
                                .addGroup(jPanel2Layout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtIdInvoice)
                                        .addComponent(txtInvoiceId))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel11)
                                        .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtSeviceId, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtUnitprice, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109,
                                        Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(Delete)
                                                .addComponent(Reset)
                                                .addComponent(btnMoveFirst)
                                                .addComponent(btnMovePrevious)
                                                .addComponent(btnMoveNext)
                                                .addComponent(btnMoveLast))
                                        .addGroup(jPanel2Layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(Create)
                                                .addComponent(Update)))
                                .addGap(19, 19, 19)));

        tabs.addTab("Biểu Mẫu", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tabs));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tabs));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMoveFirstActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnMoveFirstActionPerformed
        this.moveFirst();
    }// GEN-LAST:event_btnMoveFirstActionPerformed

    private void btnMoveLastActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnMoveLastActionPerformed
        this.moveLast();
    }// GEN-LAST:event_btnMoveLastActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_UpdateActionPerformed

        this.update();
    }// GEN-LAST:event_UpdateActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_DeleteActionPerformed

        this.delete();
    }// GEN-LAST:event_DeleteActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ResetActionPerformed

        this.clear();
    }// GEN-LAST:event_ResetActionPerformed

    private void btnMovePreviousActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnMovePreviousActionPerformed

        this.movePrevious();
    }// GEN-LAST:event_btnMovePreviousActionPerformed

    private void btnMoveNextActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnMoveNextActionPerformed

        this.moveNext();
    }// GEN-LAST:event_btnMoveNextActionPerformed

    private void txtIdInvoiceActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtIdInvoiceActionPerformed

    }// GEN-LAST:event_txtIdInvoiceActionPerformed

    private void txtSeviceIdActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtSeviceIdActionPerformed

    }// GEN-LAST:event_txtSeviceIdActionPerformed

    private void txtQuantityActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtQuantityActionPerformed

    }// GEN-LAST:event_txtQuantityActionPerformed

    private void txtInvoiceIdActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtInvoiceIdActionPerformed

    }// GEN-LAST:event_txtInvoiceIdActionPerformed

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtTotalActionPerformed

    }// GEN-LAST:event_txtTotalActionPerformed

    private void txtUnitpriceActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtUnitpriceActionPerformed

    }// GEN-LAST:event_txtUnitpriceActionPerformed

    private void CreateActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_CreateActionPerformed

        this.create();
    }// GEN-LAST:event_CreateActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {// GEN-FIRST:event_formWindowOpened

        this.open();
    }// GEN-LAST:event_formWindowOpened

    private void btnCheckAllActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnCheckAllActionPerformed

        this.checkAll();
    }// GEN-LAST:event_btnCheckAllActionPerformed

    private void btnUnCheckAllActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnUnCheckAllActionPerformed

        this.uncheckAll();
    }// GEN-LAST:event_btnUnCheckAllActionPerformed

    private void btnDeleteCheckedItemsActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnDeleteCheckedItemsActionPerformed

        this.delete();
    }// GEN-LAST:event_btnDeleteCheckedItemsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InvoiceDetailsManagerJDialog.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InvoiceDetailsManagerJDialog.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InvoiceDetailsManagerJDialog.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InvoiceDetailsManagerJDialog.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                InvoiceDetailsManagerJDialog dialog = new InvoiceDetailsManagerJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Create;
    private javax.swing.JButton Delete;
    private javax.swing.JButton Reset;
    private javax.swing.JButton Update;
    private javax.swing.JButton btnCheckAll;
    private javax.swing.JButton btnDeleteCheckedItems;
    private javax.swing.JButton btnMoveFirst;
    private javax.swing.JButton btnMoveLast;
    private javax.swing.JButton btnMoveNext;
    private javax.swing.JButton btnMovePrevious;
    private javax.swing.JButton btnUnCheckAll;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTabbedPane tabs;
    private javax.swing.JTable tblInvoiceDetails;
    private javax.swing.JTextField txtIdInvoice;
    private javax.swing.JTextField txtInvoiceId;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtSeviceId;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtUnitprice;
    // End of variables declaration//GEN-END:variables

    @Override
    public void open() {
        int selectedRow = tblInvoiceDetails.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một dòng.");
            return;
        }

        String id = tblInvoiceDetails.getValueAt(selectedRow, 1).toString();
        InvoiceDetail detail = dao.findById(id);

        if (detail != null) {
            setForm(detail);
        } else {
            JOptionPane.showMessageDialog(this, "Không tìm thấy chi tiết hóa đơn.");
        }
    }

    @Override
    public void setForm(InvoiceDetail entity) {
        txtIdInvoice.setText(String.valueOf(entity.getId()));
        txtInvoiceId.setText(String.valueOf(entity.getInvoiceId()));
        txtSeviceId.setText(String.valueOf(entity.getServiceId()));
        txtQuantity.setText(String.valueOf(entity.getQuantity()));
        txtUnitprice.setText(entity.getUnitPrice().toString());
        txtTotal.setText(entity.getSubtotal().toString());
        txtIdInvoice.setEditable(false);
    }

    @Override
    public InvoiceDetail getForm() {
        InvoiceDetail entity = new InvoiceDetail();
        try {
            entity.setInvoiceId(Integer.parseInt(txtIdInvoice.getText().trim()));
            entity.setServiceId(Integer.parseInt(txtInvoiceId.getText().trim()));
            entity.setQuantity(Integer.parseInt(txtQuantity.getText().trim()));
            entity.setUnitPrice(new BigDecimal(txtUnitprice.getText().trim()));
            entity.setSubtotal(new BigDecimal(txtTotal.getText().trim()));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Dữ liệu không hợp lệ: " + e.getMessage());
            return null;
        }
        return entity;
    }

    @Override
    public void fillToTable() {
        DefaultTableModel model = (DefaultTableModel) tblInvoiceDetails.getModel();
        model.setRowCount(0);
        try {
            List<InvoiceDetail> list = dao.findAll();
            for (InvoiceDetail detail : list) {
                model.addRow(new Object[] {
                        detail.getId(),
                        detail.getInvoiceId(),
                        detail.getServiceId(),
                        detail.getQuantity(),
                        detail.getUnitPrice(),
                        detail.getSubtotal()
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi truy vấn dữ liệu!");
        }
    }

    @Override
    public void edit() {

    }

    @Override
    public void create() {
        String invoiceIdStr = txtInvoiceId.getText().trim();
        if (invoiceIdStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Tạo mới trống mã hóa đơn", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (!invoiceIdStr.matches("\\d+")) {
            JOptionPane.showMessageDialog(this, "Mã hóa đơn sai định dạng", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String serviceIdStr = txtSeviceId.getText().trim();
        if (serviceIdStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Trống mã dịch vụ", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (!serviceIdStr.matches("\\d+")) {
            JOptionPane.showMessageDialog(this, "Mã dịch vụ sai định dạng", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String quantityStr = txtQuantity.getText().trim();
        if (quantityStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Trống số lượng", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (!quantityStr.matches("\\d+")) {
            JOptionPane.showMessageDialog(this, "Số lượng sai định dạng", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String priceStr = txtUnitprice.getText().trim();
        if (priceStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Trống giá tiền", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (!priceStr.matches("\\d+(\\.\\d+)?")) {
            JOptionPane.showMessageDialog(this, "Giá tiền sai định dạng", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String totalStr = txtTotal.getText().trim();
        if (totalStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Trống tổng", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (!totalStr.matches("\\d+(\\.\\d+)?")) {
            JOptionPane.showMessageDialog(this, "Tổng sai định dạng", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }
        try {
            InvoiceDetail detail = getForm();
            dao.create(detail);
            fillToTable();
            clear();
            JOptionPane.showMessageDialog(this, "Thêm mới thành công!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Thêm mới thất bại!");
        }
    }

    @Override
    public void update() {
        String invoiceIdStr = txtInvoiceId.getText().trim();
        if (invoiceIdStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Cập nhật trống mã hóa đơn", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (!invoiceIdStr.matches("\\d+")) {
            JOptionPane.showMessageDialog(this, "Mã hóa đơn sai định dạng", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String serviceIdStr = txtSeviceId.getText().trim();
        if (serviceIdStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Trống mã dịch vụ", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (!serviceIdStr.matches("\\d+")) {
            JOptionPane.showMessageDialog(this, "Mã dịch vụ sai định dạng", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String quantityStr = txtQuantity.getText().trim();
        if (quantityStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Trống số lượng", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (!quantityStr.matches("\\d+")) {
            JOptionPane.showMessageDialog(this, "Số lượng sai định dạng", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String priceStr = txtUnitprice.getText().trim();
        if (priceStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Trống giá tiền", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (!priceStr.matches("\\d+(\\.\\d+)?")) {
            JOptionPane.showMessageDialog(this, "Giá tiền sai định dạng", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String totalStr = txtTotal.getText().trim();
        if (totalStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Trống tổng", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (!totalStr.matches("\\d+(\\.\\d+)?")) {
            JOptionPane.showMessageDialog(this, "Tổng sai định dạng", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }
        try {
            InvoiceDetail detail = getForm();
            dao.update(detail);
            fillToTable();
            JOptionPane.showMessageDialog(this, "Cập nhật thành công!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Cập nhật thất bại!");
        }
    }

    @Override
    public void delete() {
        String id = txtIdInvoice.getText().trim();

        if (JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xóa?") == JOptionPane.YES_OPTION) {
            try {
                dao.deleteById(id);
                fillToTable();
                clear();
                JOptionPane.showMessageDialog(this, "Xóa thành công!");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Xóa thất bại!");
            }
        }
    }

    @Override
    public void clear() {
        String invoiceIdStr = txtInvoiceId.getText().trim();
        if (invoiceIdStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Cập nhật trống mã hóa đơn", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (!invoiceIdStr.matches("\\d+")) {
            JOptionPane.showMessageDialog(this, "Mã hóa đơn sai định dạng", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String serviceIdStr = txtSeviceId.getText().trim();
        if (serviceIdStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Trống mã dịch vụ", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (!serviceIdStr.matches("\\d+")) {
            JOptionPane.showMessageDialog(this, "Mã dịch vụ sai định dạng", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String quantityStr = txtQuantity.getText().trim();
        if (quantityStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Trống số lượng", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (!quantityStr.matches("\\d+")) {
            JOptionPane.showMessageDialog(this, "Số lượng sai định dạng", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String priceStr = txtUnitprice.getText().trim();
        if (priceStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Trống giá tiền", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (!priceStr.matches("\\d+(\\.\\d+)?")) {
            JOptionPane.showMessageDialog(this, "Giá tiền sai định dạng", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String totalStr = txtTotal.getText().trim();
        if (totalStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Trống tổng", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (!totalStr.matches("\\d+(\\.\\d+)?")) {
            JOptionPane.showMessageDialog(this, "Tổng sai định dạng", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }
        txtIdInvoice.setText("");
        txtInvoiceId.setText("");
        txtSeviceId.setText("");
        txtQuantity.setText("");
        txtUnitprice.setText("");
        txtTotal.setText("");
        row = -1;
    }

    @Override
    public void setEditable(boolean editable) {
        int row = tblInvoiceDetails.getSelectedRow();
        if (row >= 0) {
            String id = tblInvoiceDetails.getValueAt(row, 1).toString();
            InvoiceDetail detail = dao.findById(id);
            if (detail != null) {
                setForm(detail);
            }
        }
    }

    @Override
    public void checkAll() {
        tblInvoiceDetails.getSelectionModel().setValueIsAdjusting(true);
        if (tblInvoiceDetails.getRowCount() > 0) {
            tblInvoiceDetails.setRowSelectionInterval(0, tblInvoiceDetails.getRowCount() - 1);
        }

        tblInvoiceDetails.getSelectionModel().setValueIsAdjusting(false);

        JOptionPane.showMessageDialog(this, "Đã chọn tất cả!");
    }

    @Override
    public void uncheckAll() {
        if (tblInvoiceDetails.getSelectedRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Không có dòng nào để bỏ chọn!");
            return;
        }

        tblInvoiceDetails.clearSelection();
        JOptionPane.showMessageDialog(this, "Đã hủy chọn tất cả!");
    }

    @Override
    public void deleteCheckedItems() {
        if (XDialog.confirm("Bạn thực sự muốn xóa?")) {
            String id = txtIdInvoice.getText();
            dao.deleteById(id);
            this.fillToTable();
            this.clear();
        }
    }

    @Override
    public void moveFirst() {
        if (tblInvoiceDetails.getRowCount() > 0) {
            moveTo(0);
        }
    }

    @Override
    public void movePrevious() {
        int selectedRow = tblInvoiceDetails.getSelectedRow();
        if (selectedRow > 0) {
            moveTo(selectedRow - 1);
        }
    }

    @Override
    public void moveNext() {
        int selectedRow = tblInvoiceDetails.getSelectedRow();
        if (selectedRow >= 0 && selectedRow < tblInvoiceDetails.getRowCount() - 1) {
            moveTo(selectedRow + 1);
        }
    }

    @Override
    public void moveLast() {
        int rowCount = tblInvoiceDetails.getRowCount();
        if (rowCount > 0) {
            moveTo(rowCount - 1);
        }
    }

    @Override
    public void moveTo(int rowIndex) {
        if (rowIndex >= 0 && rowIndex < tblInvoiceDetails.getRowCount()) {
            tblInvoiceDetails.setRowSelectionInterval(rowIndex, rowIndex);

            txtInvoiceId.setText(tblInvoiceDetails.getValueAt(rowIndex, 0).toString());
            txtSeviceId.setText(tblInvoiceDetails.getValueAt(rowIndex, 1).toString());
            txtQuantity.setText(tblInvoiceDetails.getValueAt(rowIndex, 2).toString());
            txtUnitprice.setText(tblInvoiceDetails.getValueAt(rowIndex, 3).toString());
            txtTotal.setText(tblInvoiceDetails.getValueAt(rowIndex, 4).toString());
        } // nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

}
