/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ui.manager;

import ui.controller.PaymentManagerController;
import dao.PaymentDAO;
import impl.PaymentDAOImpl;
import entity.Invoice;
import dao.InvoiceDao;
import entity.Payment;
import impl.InvoiceDAOImpl;
import impl.PaymentDAOImpl;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.math.BigDecimal;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import utils.XDialog;

/**
 *
 * @author GAMING
 */
public class PaymentManagerJDialog extends javax.swing.JDialog implements PaymentManagerController{
    
    /**
     * Creates new form PaymentManagerJDialog
     */
    public PaymentManagerJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabs = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPayment = new javax.swing.JTable();
        btnCheckAll = new javax.swing.JButton();
        btnUnCheckAll = new javax.swing.JButton();
        btnDeleteCheckedItems = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtTenant = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtPaymentDate = new javax.swing.JTextField();
        txtPaymentMethod = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtInvoiceId = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNote = new javax.swing.JTextField();
        txtTransactionCode = new javax.swing.JTextField();
        Update = new javax.swing.JButton();
        Create = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        Reset = new javax.swing.JButton();
        btnMoveFirst = new javax.swing.JButton();
        btnMovePrevious = new javax.swing.JButton();
        btnMoveNext = new javax.swing.JButton();
        btnMoveLast = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tblPayment.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "InvoiceId", "Tenant", "Amont", "PaymentDate", "PaymentMethod", "TransactionCode", "Note"
            }
        ));
        jScrollPane1.setViewportView(tblPayment);

        btnCheckAll.setText("Chọn tất cả");
        btnCheckAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckAllActionPerformed(evt);
            }
        });

        btnUnCheckAll.setText("Hủy chọn tất cả");
        btnUnCheckAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnCheckAllActionPerformed(evt);
            }
        });

        btnDeleteCheckedItems.setText("Xóa các mục đã chọn");
        btnDeleteCheckedItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteCheckedItemsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 778, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCheckAll)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUnCheckAll)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeleteCheckedItems)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCheckAll)
                    .addComponent(btnUnCheckAll)
                    .addComponent(btnDeleteCheckedItems)))
        );

        tabs.addTab("Danh sách", jPanel1);

        jLabel12.setText("Mã Thanh Toán ");

        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });

        jLabel11.setText("Mã Người Thuê");

        txtTenant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenantActionPerformed(evt);
            }
        });

        jLabel5.setText("Ngày Thanh Toán");

        txtPaymentDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPaymentDateActionPerformed(evt);
            }
        });

        txtPaymentMethod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPaymentMethodActionPerformed(evt);
            }
        });

        jLabel6.setText("Phương Thức Thanh Toán");

        txtAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAmountActionPerformed(evt);
            }
        });

        jLabel14.setText("Tổng");

        txtInvoiceId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInvoiceIdActionPerformed(evt);
            }
        });

        jLabel13.setText("Mã Hóa Đơn");

        jLabel7.setText("Mã Giao Dịch");

        jLabel8.setText("Ghi Chú");

        txtNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNoteActionPerformed(evt);
            }
        });

        txtTransactionCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTransactionCodeActionPerformed(evt);
            }
        });

        Update.setText("Cập nhật");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });

        Create.setText("Tạo mới");
        Create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateActionPerformed(evt);
            }
        });

        Delete.setText("Xóa");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        Reset.setText("Nhập mới");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });

        btnMoveFirst.setText("|<");
        btnMoveFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoveFirstActionPerformed(evt);
            }
        });

        btnMovePrevious.setText("<<");
        btnMovePrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMovePreviousActionPerformed(evt);
            }
        });

        btnMoveNext.setText(">>");
        btnMoveNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoveNextActionPerformed(evt);
            }
        });

        btnMoveLast.setText(">|");
        btnMoveLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoveLastActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtId, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                                        .addComponent(txtTenant, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(txtPaymentDate, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPaymentMethod, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14)
                                    .addComponent(txtInvoiceId, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel13)))
                            .addComponent(jLabel7)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtTransactionCode, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNote, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))))
                        .addGap(0, 167, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel5))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Create)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Update)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Delete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Reset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMoveFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnMovePrevious, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnMoveNext, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnMoveLast, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtId)
                    .addComponent(txtInvoiceId))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTenant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPaymentDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPaymentMethod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTransactionCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Delete)
                        .addComponent(Reset)
                        .addComponent(btnMoveFirst)
                        .addComponent(btnMovePrevious)
                        .addComponent(btnMoveNext)
                        .addComponent(btnMoveLast))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Create)
                        .addComponent(Update)))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        tabs.addTab("Biểu mẫu", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabs)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabs)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void txtTenantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenantActionPerformed

    private void txtPaymentDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPaymentDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPaymentDateActionPerformed

    private void txtPaymentMethodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPaymentMethodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPaymentMethodActionPerformed

    private void txtAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAmountActionPerformed

    private void txtInvoiceIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInvoiceIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInvoiceIdActionPerformed

    private void txtNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoteActionPerformed

    private void txtTransactionCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTransactionCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTransactionCodeActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        // TODO add your handling code here:
        this.update();
    }//GEN-LAST:event_UpdateActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
        this.delete();
    }//GEN-LAST:event_DeleteActionPerformed

    private void CreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateActionPerformed
        // TODO add your handling code here:
         this.create();
    }//GEN-LAST:event_CreateActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        // TODO add your handling code here:
        this.clear();
    }//GEN-LAST:event_ResetActionPerformed

    private void btnMovePreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMovePreviousActionPerformed
        // TODO add your handling code here:
        this.movePrevious();
    }//GEN-LAST:event_btnMovePreviousActionPerformed

    private void btnMoveNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoveNextActionPerformed
        // TODO add your handling code here:
        this.moveNext();
    }//GEN-LAST:event_btnMoveNextActionPerformed

    private void btnCheckAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckAllActionPerformed
        // TODO add your handling code here:
        this.checkAll();
    }//GEN-LAST:event_btnCheckAllActionPerformed

    private void btnUnCheckAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnCheckAllActionPerformed
        // TODO add your handling code here:
        this.uncheckAll();
    }//GEN-LAST:event_btnUnCheckAllActionPerformed

    private void btnDeleteCheckedItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteCheckedItemsActionPerformed
        // TODO add your handling code here:
        this.deleteCheckedItems();
        
    }//GEN-LAST:event_btnDeleteCheckedItemsActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        this.open();
    }//GEN-LAST:event_formWindowOpened

    private void btnMoveFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoveFirstActionPerformed
        // TODO add your handling code here:
        this.moveFirst();
    }//GEN-LAST:event_btnMoveFirstActionPerformed

    private void btnMoveLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoveLastActionPerformed
        // TODO add your handling code here:
        this.moveLast();
    }//GEN-LAST:event_btnMoveLastActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaymentManagerJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaymentManagerJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaymentManagerJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaymentManagerJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PaymentManagerJDialog dialog = new PaymentManagerJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.open();
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Create;
    private javax.swing.JButton Delete;
    private javax.swing.JButton Reset;
    private javax.swing.JButton Update;
    private javax.swing.JButton btnCheckAll;
    private javax.swing.JButton btnDeleteCheckedItems;
    private javax.swing.JButton btnMoveFirst;
    private javax.swing.JButton btnMoveLast;
    private javax.swing.JButton btnMoveNext;
    private javax.swing.JButton btnMovePrevious;
    private javax.swing.JButton btnUnCheckAll;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane tabs;
    private javax.swing.JTable tblPayment;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtInvoiceId;
    private javax.swing.JTextField txtNote;
    private javax.swing.JTextField txtPaymentDate;
    private javax.swing.JTextField txtPaymentMethod;
    private javax.swing.JTextField txtTenant;
    private javax.swing.JTextField txtTransactionCode;
    // End of variables declaration//GEN-END:variables
    PaymentDAO dao = new PaymentDAOImpl();
    InvoiceDao invoiceDAO = new InvoiceDAOImpl();
    
    List<Payment> items = List.of();
    private int currentRow = -1;
    
    @Override
    public void open() {
        this.setLocationRelativeTo(null);
        this.fillToTable();
        this.clear();

        tblPayment.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                this.edit();
            }
        });

        tblPayment.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 1) {
                    edit();
                }
            }
        });
        if (!items.isEmpty()) {
    tblPayment.setRowSelectionInterval(0, 0);
    edit();
}
    }

    @Override
    public void setForm(Payment entity) {
    txtId.setText(String.valueOf(entity.getId()));
    txtInvoiceId.setText(String.valueOf(entity.getInvoiceId()));
    txtTenant.setText(String.valueOf(entity.getTenant()));
    txtAmount.setText(String.valueOf(entity.getAmount()));
    txtPaymentDate.setText(String.valueOf(entity.getPaymentDate()));
    txtPaymentMethod.setText(String.valueOf(entity.getPaymentMethod()));
    txtTransactionCode.setText(String.valueOf(entity.getTransactionCode()));
    txtNote.setText(String.valueOf(entity.getNote()));
    }

    @Override
    public Payment getForm() {
        return getForm(false); 
    }
    public Payment getForm(boolean isCreate) {
        Payment p = new Payment();

    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");

    if (!isCreate) {
        p.setId(Integer.parseInt(txtId.getText())); 
    }

    p.setInvoiceId(Integer.parseInt(txtInvoiceId.getText())); 
    p.setTenant(txtTenant.getText());                          
    p.setAmount(new BigDecimal(txtAmount.getText()));           

    try {
        Date date = sdf.parse(txtPaymentDate.getText());        
        p.setPaymentDate(date);
    } catch (Exception e) {
        throw new RuntimeException("Ngày thanh toán không hợp lệ", e);
    }

    p.setPaymentMethod(txtPaymentMethod.getText());            
    p.setTransactionCode(txtTransactionCode.getText());        
    p.setNote(txtNote.getText());                                

    return p;
    }

    @Override
public void fillToTable() {
    DefaultTableModel model = (DefaultTableModel) tblPayment.getModel();
    model.setRowCount(0);

    try {
        items = dao.findAll();
        for (Payment item : items) {
            Object[] rowData = {
                item.getId(),                    
                item.getInvoiceId(),              
                item.getTenant(),               
                item.getAmount(),           
                item.getPaymentDate(),              
                item.getPaymentMethod(),        
                item.getTransactionCode(), 
                item.getNote(),
            };
            model.addRow(rowData);
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Lỗi khi tải dữ liệu hợp đồng: " + e.getMessage());
        e.printStackTrace();
    }
}

    @Override
    public void edit() {
        int row = tblPayment.getSelectedRow();
        if (row >= 0 && row < items.size()) {
            Payment entity = items.get(row);
            this.setForm(entity);
            this.setEditable(true);
            tabs.setSelectedIndex(1);
        }
    }



    @Override
public void create() {
    try {
        String invoiceId = txtInvoiceId.getText().trim();

        // Kiểm tra invoiceId có tồn tại không
        Invoice invoice = invoiceDAO.findById(invoiceId);
        if (invoice == null) {
            JOptionPane.showMessageDialog(this, "InvoiceId không tồn tại!");
            return;
        }

        // Lấy CCCD người thuê
        String tenant = txtTenant.getText().trim();
        if (!tenant.matches("\\d{12}")) {
            JOptionPane.showMessageDialog(this, "CCCD không hợp lệ (phải đủ 12 chữ số, không chứa chữ cái)");
            return;
        }

        // Lấy số tiền từ Invoice
        BigDecimal amount = invoice.getTotalamount();

        // Ngày thanh toán = ngày hiện tại
        Date paymentDate = new Date();

        // Phương thức thanh toán
        String method = txtPaymentMethod.getText().trim();
        if (method.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập phương thức thanh toán");
            return;
        }

        // Mã giao dịch (có thể kiểm tra độ dài/tùy format)
        String transactionCode = txtTransactionCode.getText().trim();
        if (transactionCode.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập mã giao dịch");
            return;
        }

        // Ghi chú (không bắt buộc)
        String note = txtNote.getText().trim();

        // Tạo đối tượng Payment
        Payment payment = Payment.builder()
            .InvoiceId(Integer.parseInt(invoiceId))
            .Tenant(tenant)
            .Amount(amount)
            .PaymentDate(paymentDate)
            .PaymentMethod(method)
            .TransactionCode(transactionCode)
            .Note(note)
            .build();

        // Gọi DAO để lưu
        dao.create(payment);
        JOptionPane.showMessageDialog(this, "Tạo thanh toán thành công!");

        loadDataToTable(); // làm mới bảng nếu có
        clear();

    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "InvoiceId phải là số nguyên!");
    } catch (Exception ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Lỗi: " + ex.getMessage());
    }
}
    public void update() {
         try {
        Payment p = getForm(false);
        dao.update(p);
        fillToTable();
        clear();
        JOptionPane.showMessageDialog(this, "Cập nhật thành công!");
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Lỗi cập nhật: " + ex.getMessage());
        ex.printStackTrace();
    }
}

    @Override
    public void delete() {
        if (XDialog.confirm("Bạn thực sự muốn xóa?")) {
        String id = txtId.getText();
        dao.deleteById(id);
        this.fillToTable();
        this.clear();
    }
}

    @Override
    public void clear() {
    txtId.setText("");
    txtInvoiceId.setText("");
    txtTenant.setText("");
    txtAmount.setText("");
    txtPaymentDate.setText("");
    txtPaymentMethod.setText("");
    txtTransactionCode.setText("");
    txtNote.setText("");
    currentRow = -1;
}

    @Override
    public void setEditable(boolean editable) {
    txtInvoiceId.setEditable(editable);
    txtTenant.setEditable(editable);
    txtAmount.setEditable(editable);
    txtPaymentDate.setEditable(editable);
    txtPaymentMethod.setEditable(editable);
    txtTransactionCode.setEditable(editable);
    txtNote.setEditable(editable);
    Create.setEnabled(editable);
    Update.setEnabled(editable);
    Delete.setEnabled(editable);
}

    @Override
    public void checkAll() {
         tblPayment.setRowSelectionInterval(0, tblPayment.getRowCount() - 1);
}

    @Override
    public void uncheckAll() {
        tblPayment.clearSelection();
}

    @Override
    public void deleteCheckedItems() {
        int row = tblPayment.getSelectedRow();
    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Chọn một dòng để xóa");
        return;
    }

    Payment item = items.get(row);
    if (XDialog.confirm("Bạn có chắc chắn muốn xóa thanh toán này?")) {
        dao.deleteById(String.valueOf(item.getId()));
        this.fillToTable();
        JOptionPane.showMessageDialog(this, "Đã xóa!");
    }
}

    @Override
    public void moveFirst() {
        if (!items.isEmpty()) {
        currentRow = 0;
        tblPayment.setRowSelectionInterval(currentRow, currentRow);
        edit();
    }
}

    @Override
    public void movePrevious() {
        if (currentRow > 0) {
        currentRow--;
        tblPayment.setRowSelectionInterval(currentRow, currentRow);
        edit();
    }
}
    @Override
    public void moveNext() {
        if (currentRow < items.size() - 1) {
        currentRow++;
        tblPayment.setRowSelectionInterval(currentRow, currentRow);
        edit();
    }
}

    @Override
    public void moveLast() {
        if (!items.isEmpty()) {
        currentRow = items.size() - 1;
        tblPayment.setRowSelectionInterval(currentRow, currentRow);
        edit();
    }
}

    @Override
    public void moveTo(int rowIndex) {
       if (rowIndex >= 0 && rowIndex < items.size()) {
        currentRow = rowIndex;
        tblPayment.setRowSelectionInterval(currentRow, currentRow);
        edit();
    }
}
    private void loadDataToTable() {
    // Gợi ý: Gọi lại DAO để load tất cả Payment rồi đổ vào JTable
    List<Payment> payments = dao.findAll();
    DefaultTableModel model = (DefaultTableModel) tblPayment.getModel();
    model.setRowCount(0); // clear bảng cũ
    for (Payment p : payments) {
        model.addRow(new Object[]{
            p.getId(),
            p.getInvoiceId(),
            p.getTenant(),
            p.getAmount(),
            p.getPaymentDate(),
            p.getPaymentMethod(),
            p.getTransactionCode(),
            p.getNote()
        });
    }
}
}
